name: kapua-continuous-integration
on: [push, pull_request] # Triggers the workflow on push or pull request events

env:
  BUILD_OPTS: ""
  CONFIG_OVERRIDES: "-Dcommons.db.schema=kapuadb -Dcommons.settings.hotswap=true -Dbroker.host=localhost"
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  build-kapua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v1
        with:
          java-version: '8' # The JDK version to make available on the path.
          # java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          # architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/cache@v2 # Cache local Maven repository to reuse dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -v
      - run: mvn -B ${BUILD_OPTS} -DskipTests clean install
#  test-brokerAcl:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @brokerAcl" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-tag:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @tag" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-broker:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @broker" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-device:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @device" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-connection:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @connection" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-datastore:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @datastore" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-user:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @user" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-security:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @security" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobs:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobs" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-triggerService:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @triggerService" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-account:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @account" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineStartOfflineDevice:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineStartOfflineDevice" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineStartOnlineDevice:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineStartOnlineDevice" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineRestartOfflineDevice:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOfflineDevice" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineRestartOnlineDevice:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOnlineDevice" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineRestartOnlineDeviceSecondPart:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOnlineDeviceSecondPart" verify
##      - uses: actions/checkout@v2
##      - uses: codecov/codecov-action@v1
#  test-jobEngineServiceStop:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - uses: nick-invision/retry@v2.4.0
#        with:
#          timeout_minutes: 30
#          retry_on: error
#          max_attempts: 3
#          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineServiceStop" verify
##        - uses: actions/checkout@v2
##        - uses: codecov/codecov-action@v1
  junit-tests:
    needs: build-kapua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='org.eclipse.kapua.qa.markers.junit.JUnitTests' verify
#      - uses: actions/checkout@v2
#      - uses: codecov/codecov-action@v1
#  build-javadoc:
#    needs: build-kapua
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - run: mvn -B -DskipTests install javadoc:jar
#      - uses: actions/checkout@v2
#      - uses: codecov/codecov-action@v1
  test-coverage:
    needs: [build-kapua, junit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
      - run: bash <(curl -s https://codecov.io/bash)

#    steps:
#      - uses: actions/checkout@v2
#      - uses: r-lib/actions/setup-r@v1
#      - uses: r-lib/actions/setup-pandoc@v1
#
#      - name: Query dependencies
#        run: |
#          install.packages('remotes')
#          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
#          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
#        shell: Rscript {0}
#
#      - name: Cache R packages
#        uses: actions/cache@v2
#        with:
#          path: ${{ env.R_LIBS_USER }}
#          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
#          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
#
#      - name: Install dependencies
#        run: |
#          install.packages(c("remotes"))
#          remotes::install_deps(dependencies = TRUE)
#          remotes::install_cran("covr")
#        shell: Rscript {0}
#
#      - name: Test coverage
#        run: covr::codecov()
#        shell: Rscript {0}